### ISSUE TITLE
Livery settings are being registered as default configuration, even after I change them.

### ISSUE THREAD

**Issue by MaximussDev** [magknight/787aviatorsTracker#291]
Hey.

So, I've been attempting to make custom PA Announcements, and I've run into a problem: I can't load them.  I've edited the soundpack JSON file to make my cabinAnnouncements load the custom WestJet ones I've made, but it still loads the default.

1. Download a livery (or duplicate an existing one)
2. Go into the livery's soundpack file
3. Change the cabinAnnouncements in the soundpack file
4. Load the aircraft

The expected behavior was: the COMM tab would say, "WestJet soundpack," instead of, "default soundpack."

Screenshots:
![B7879 - 2020-03-01 13 38 57](https://user-images.githubusercontent.com/61666157/75633458-1d34bd00-5bc2-11ea-8252-b5b47a54a59a.png)

**Desktop (please complete the following information):**
 - Windows 10
 - X-Plane 11.41
 - Version 1.4.0

I talked to aeroniemi on Discord and I was referred to this.  He confirmed the issue was that the code was registering me as in the default livery, instead of the WestJet one (as it should've been).

Thanks!

**Comment by KBNOtaku** [comment]
@MaximussDev 
I also see that problem!
Do the Livery Information for the Aircraft get loaded? Can be seen to the left from the PFD where the clock is. If not have you tried to reload the Aircraft through the Developer Menu?
I will also add my report about this bug with a video here!

**Comment by MaximussDev** [comment]
Hello!  I’m not sure.  The livery is loaded, but the code, as aeroniemi
says, “is registering me as being in a default livery.”

Thanks!

**Comment by aeroniemi** [comment]
the issue here seems to be specifically that the soundpack isn't changing (order of operations issue) - this has been fixed for 1.4.5, but nothing else changed

**Comment by KBNOtaku** [comment]
The settings file still doesn´t load initial, only when reloading the Aircraft!?
